[package]
name = "yui"
version = "0.1.0"
authors = ["rayes <70722312+rayes0@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "8.0.0"
home = "0.5.3"
colored = "2"
